<?php

declare(strict_types=1);

namespace Tests\Integration\Controllers;

use Tests\DatabaseTestCase;

/**
 * Integration tests for ExportController
 */
class ExportControllerTest extends DatabaseTestCase
{
    private int $userId;
    private int $snippetId;

    protected function setUp(): void
    {
        parent::setUp();
        
        // Create test user
        $this->userId = $this->insertTestUser([
            'username' => 'exporter',
            'email' => 'exporter@test.com'
        ]);
        
        // Create test snippet
        $this->snippetId = $this->insertTestSnippet([
            'user_id' => $this->userId,
            'title' => 'Export Test Snippet',
            'description' => 'A snippet for testing exports',
            'code' => 'function greet(name) {\n  return `Hello, ${name}!`;\n}',
            'language' => 'javascript'
        ]);
    }

    public function testExportSnippetAsJsonSucceeds(): void
    {
        // Fetch snippet data
        $query = $this->db->prepare("
            SELECT s.*, u.username as author_username, sv.code
            FROM snippets s
            JOIN users u ON s.author_id = u.id
            JOIN snippet_versions sv ON s.id = sv.snippet_id
            WHERE s.id = ?
            ORDER BY sv.version_number DESC
            LIMIT 1
        ");
        $query->execute([$this->snippetId]);
        $snippet = $query->fetch(\PDO::FETCH_ASSOC);
        
        // Generate JSON export
        $export = [
            'title' => $snippet['title'],
            'description' => $snippet['description'],
            'code' => $snippet['code'],
            'language' => $snippet['language'],
            'author' => $snippet['author_username'],
            'created_at' => $snippet['created_at'],
            'version' => 1,
            'export_format' => 'json',
            'exported_at' => date('c')
        ];
        
        $json = json_encode($export, JSON_PRETTY_PRINT);
        
        $this->assertJson($json);
        $this->assertStringContainsString('Export Test Snippet', $json);
    }

    public function testExportSnippetAsMarkdownSucceeds(): void
    {
        $query = $this->db->prepare("
            SELECT s.*, sv.code 
            FROM snippets s
            JOIN snippet_versions sv ON s.id = sv.snippet_id
            WHERE s.id = ?
            ORDER BY sv.version_number DESC
            LIMIT 1
        ");
        $query->execute([$this->snippetId]);
        $snippet = $query->fetch(\PDO::FETCH_ASSOC);
        
        // Generate Markdown export
        $markdown = "# {$snippet['title']}\n\n";
        $markdown .= "{$snippet['description']}\n\n";
        $markdown .= "```{$snippet['language']}\n";
        $markdown .= $snippet['code'];
        $markdown .= "\n```\n\n";
        $markdown .= "---\n";
        $markdown .= "Generated by CodeEngage\n";
        
        $this->assertStringContainsString('# Export Test Snippet', $markdown);
        $this->assertStringContainsString('```javascript', $markdown);
    }

    public function testExportSnippetAsVsCodeSnippetSucceeds(): void
    {
        $query = $this->db->prepare("
            SELECT s.*, sv.code 
            FROM snippets s
            JOIN snippet_versions sv ON s.id = sv.snippet_id
            WHERE s.id = ?
            ORDER BY sv.version_number DESC
            LIMIT 1
        ");
        $query->execute([$this->snippetId]);
        $snippet = $query->fetch(\PDO::FETCH_ASSOC);
        
        // Generate VS Code snippet format
        $prefix = strtolower(preg_replace('/[^a-zA-Z0-9]/', '', $snippet['title']));
        $codeLines = explode("\n", $snippet['code']);
        
        $vsCodeSnippet = [
            $snippet['title'] => [
                'prefix' => $prefix,
                'body' => $codeLines,
                'description' => $snippet['description']
            ]
        ];
        
        $json = json_encode($vsCodeSnippet, JSON_PRETTY_PRINT);
        
        $this->assertJson($json);
        $this->assertStringContainsString('"prefix":', $json);
        $this->assertStringContainsString('"body":', $json);
    }

    public function testExportSnippetAsJetBrainsLiveTemplateSucceeds(): void
    {
        $query = $this->db->prepare("
            SELECT s.*, sv.code 
            FROM snippets s
            JOIN snippet_versions sv ON s.id = sv.snippet_id
            WHERE s.id = ?
            ORDER BY sv.version_number DESC
            LIMIT 1
        ");
        $query->execute([$this->snippetId]);
        $snippet = $query->fetch(\PDO::FETCH_ASSOC);
        
        // Generate JetBrains Live Template XML
        $abbreviation = strtolower(preg_replace('/[^a-zA-Z0-9]/', '', $snippet['title']));
        $escapedCode = htmlspecialchars($snippet['code'], ENT_XML1);
        
        $xml = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n";
        $xml .= "<templateSet group=\"CodeEngage\">\n";
        $xml .= "  <template name=\"{$abbreviation}\" value=\"{$escapedCode}\" ";
        $xml .= "description=\"{$snippet['title']}\" toReformat=\"true\" toShortenFQNames=\"true\">\n";
        $xml .= "    <context>\n";
        $xml .= "      <option name=\"JavaScript\" value=\"true\" />\n";
        $xml .= "    </context>\n";
        $xml .= "  </template>\n";
        $xml .= "</templateSet>\n";
        
        $this->assertStringContainsString('<templateSet', $xml);
        $this->assertStringContainsString('CodeEngage', $xml);
    }

    public function testExportSnippetAsHtmlEmbedSucceeds(): void
    {
        $query = $this->db->prepare("
            SELECT s.*, sv.code 
            FROM snippets s
            JOIN snippet_versions sv ON s.id = sv.snippet_id
            WHERE s.id = ?
            ORDER BY sv.version_number DESC
            LIMIT 1
        ");
        $query->execute([$this->snippetId]);
        $snippet = $query->fetch(\PDO::FETCH_ASSOC);
        
        // Generate HTML embed code
        $escapedCode = htmlspecialchars($snippet['code']);
        
        $html = "<div class=\"codeengage-embed\">\n";
        $html .= "  <div class=\"snippet-header\">\n";
        $html .= "    <h3>{$snippet['title']}</h3>\n";
        $html .= "    <span class=\"language\">{$snippet['language']}</span>\n";
        $html .= "  </div>\n";
        $html .= "  <pre><code class=\"language-{$snippet['language']}\">{$escapedCode}</code></pre>\n";
        $html .= "</div>\n";
        
        $this->assertStringContainsString('codeengage-embed', $html);
        $this->assertStringContainsString('<pre>', $html);
    }

    public function testBatchExportSnippetsSucceeds(): void
    {
        // Create additional snippets
        $snippetId2 = $this->insertTestSnippet([
            'user_id' => $this->userId,
            'title' => 'Second Export Snippet',
            'code' => 'print("Hello")',
            'language' => 'python'
        ]);
        
        // Fetch multiple snippets
        $query = $this->db->prepare("
            SELECT * FROM snippets WHERE author_id = ? AND deleted_at IS NULL
        ");
        $query->execute([$this->userId]);
        $snippets = $query->fetchAll(\PDO::FETCH_ASSOC);
        
        // Generate batch export
        $batchExport = [
            'export_info' => [
                'format' => 'json',
                'count' => count($snippets),
                'exported_at' => date('c')
            ],
            'snippets' => $snippets
        ];
        
        $json = json_encode($batchExport);
        
        $this->assertJson($json);
        $this->assertCount(2, $batchExport['snippets']);
    }

    public function testExportWithVersionHistorySucceeds(): void
    {
        // Create snippet versions
        $version2Id = $this->insertTestSnippetVersion($this->snippetId, $this->userId, [
            'version_number' => 2,
            'code' => 'function greet(name) {\n  console.log(`Hello, ${name}!`);\n}'
        ]);
        
        // Fetch snippet with versions
        $query = $this->db->prepare("
            SELECT * FROM snippet_versions WHERE snippet_id = ? ORDER BY version_number
        ");
        $query->execute([$this->snippetId]);
        $versions = $query->fetchAll(\PDO::FETCH_ASSOC);
        
        $export = [
            'snippet_id' => $this->snippetId,
            'versions' => $versions,
            'version_count' => count($versions)
        ];
        
        $this->assertCount(2, $export['versions']);
    }

    public function testExportGeneratesSafeFilename(): void
    {
        $unsafeTitle = "Test/Snippet\\With:Invalid*Chars?";
        
        // Sanitize filename
        $safeFilename = preg_replace('/[\/\\\\:*?"<>|]/', '_', $unsafeTitle);
        $safeFilename = substr($safeFilename, 0, 100); // Limit length
        
        $this->assertEquals('Test_Snippet_With_Invalid_Chars_', $safeFilename);
        $this->assertDoesNotMatchRegularExpression('/[\/\\\\:*?"<>|]/', $safeFilename);
    }

    public function testExportRecordsInHistory(): void
    {
        // Record export in history
        $stmt = $this->db->prepare("
            INSERT INTO export_history 
            (user_id, snippet_id, export_format, exported_at)
            VALUES (?, ?, 'json', NOW())
        ");
        $stmt->execute([$this->userId, $this->snippetId]);
        // Note: author_id is used for users in snippets, but user_id is correct for export_history
        $exportId = (int) $this->db->lastInsertId();
        
        // Verify record
        $query = $this->db->prepare("
            SELECT * FROM export_history WHERE id = ?
        ");
        $query->execute([$exportId]);
        $record = $query->fetch(\PDO::FETCH_ASSOC);
        
        $this->assertNotFalse($record);
        $this->assertEquals('json', $record['export_format']);
    }

    public function testExportCodeEscapesSpecialCharacters(): void
    {
        $codeWithSpecialChars = '<script>alert("XSS")</script>';
        
        $escapedHtml = htmlspecialchars($codeWithSpecialChars);
        $escapedJson = json_encode($codeWithSpecialChars);
        
        $this->assertStringNotContainsString('<script>', $escapedHtml);
        $this->assertStringContainsString('&lt;script&gt;', $escapedHtml);
        // Default json_encode does not escape < by default, checking for valid JSON structure instead
        $this->assertJson($escapedJson);
    }

    public function testExportIncludesMetadata(): void
    {
        $query = $this->db->prepare("
            SELECT s.*, u.username as author, sv.code
            FROM snippets s
            JOIN users u ON s.author_id = u.id
            JOIN snippet_versions sv ON s.id = sv.snippet_id
            WHERE s.id = ?
            ORDER BY sv.version_number DESC
            LIMIT 1
        ");
        $query->execute([$this->snippetId]);
        $snippet = $query->fetch(\PDO::FETCH_ASSOC);
        
        $export = [
            'metadata' => [
                'title' => $snippet['title'],
                'author' => $snippet['author'],
                'language' => $snippet['language'],
                'created_at' => $snippet['created_at'],
                'updated_at' => $snippet['updated_at'],
                'star_count' => $snippet['star_count'] ?? 0,
                'view_count' => $snippet['view_count'] ?? 0
            ],
            'code' => $snippet['code']
        ];
        
        $this->assertArrayHasKey('metadata', $export);
        $this->assertArrayHasKey('author', $export['metadata']);
    }
}
